services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - .:/app
    networks:
      - notification-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - notification-network

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge

volumes:
  rabbitmq_data:
  mongodb_data:
